#!/usr/bin/env node
/**
 * Builds one complete, demonstrable project by driving the real HTTP API.
 *
 * Nothing here writes to the database directly. Every step is the same request
 * the portal makes, in the same order a human would make it — owner drafts,
 * DPO approves, agent collects, subject consents. That is deliberate: a seed
 * that INSERTs rows can produce a state the application itself can never reach,
 * and a demo built on one is a demo of the seed script.
 *
 * What it produces:
 *
 *   1 project      APPROVED by the DPO, agent assigned
 *   2 subjects     registered, consented, face-enrolled and voice-enrolled
 *   1 IMAGE session   12 photos, bulk-uploaded, ended -> recognition pipeline
 *   1 AUDIO session   the two-speaker interview, analysed and redacted
 *   1 TEXT session    a document with PII, analysed and redacted
 *   1 video           attached to the image session, analysed
 *
 * Fixtures come from tests/fixtures (see the README there). The image set is
 * generated by scripts/make-bulk-fixtures.js; the audio is synthesised locally.
 *
 * Usage:
 *   node scripts/demo-seed.js                 # build everything
 *   node scripts/demo-seed.js --skip-media    # governance + subjects only
 */
import 'dotenv/config'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const FIXTURES = path.join(HERE, '..', 'tests', 'fixtures')
const BASE = process.env.DEMO_API_URL ?? 'http://127.0.0.1:4000'
const PASSWORD = process.env.DEV_ADMIN_PASSWORD ?? 'Prism@2026!'
const SKIP_MEDIA = process.argv.includes('--skip-media')

// A short run tag so repeated runs are distinguishable in the portal rather than
// colliding on name. Not random: a timestamp sorts, which matters when the
// session list has thirty rows in it.
const TAG = new Date().toISOString().slice(5, 16).replace(/[-:T]/g, '')

// ---------------------------------------------------------------------------
// A cookie jar, because the API authenticates with HttpOnly cookies and
// node:fetch has no jar of its own. One jar per principal — sharing one would
// let the agent's session silently overwrite the subject's.
// ---------------------------------------------------------------------------
class Jar {
  constructor(label) {
    this.label = label
    this.cookies = new Map()
  }

  absorb(res) {
    for (const raw of res.headers.getSetCookie?.() ?? []) {
      const [pair] = raw.split(';')
      const idx = pair.indexOf('=')
      if (idx > 0) this.cookies.set(pair.slice(0, idx).trim(), pair.slice(idx + 1).trim())
    }
  }

  header() {
    return [...this.cookies].map(([k, v]) => `${k}=${v}`).join('; ')
  }
}

async function call(jar, method, url, { json, form, expect } = {}) {
  const headers = {}
  const cookie = jar?.header()
  if (cookie) headers.Cookie = cookie
  if (json) headers['Content-Type'] = 'application/json'

  const res = await fetch(`${BASE}${url}`, {
    method,
    headers,
    body: json ? JSON.stringify(json) : form,
  })
  jar?.absorb(res)

  const text = await res.text()
  let body
  try {
    body = text ? JSON.parse(text) : null
  } catch {
    body = text
  }

  const ok = expect ? expect.includes(res.status) : res.ok
  if (!ok) {
    const detail = typeof body === 'object' ? JSON.stringify(body) : String(body).slice(0, 300)
    throw new Error(`${method} ${url} -> ${res.status} ${detail}`)
  }
  return body
}

// ---------------------------------------------------------------------------

const step = (n, msg) => console.log(`\n[${n}] ${msg}`)
const ok = (msg) => console.log(`    ok  ${msg}`)
const note = (msg) => console.log(`    ..  ${msg}`)

async function adminLogin(email) {
  const jar = new Jar(email)
  await call(jar, 'POST', '/auth/admin/login', { json: { email, password: PASSWORD } })
  return jar
}

/**
 * Registers a data principal and signs them in.
 *
 * The OTP is read from the register/login response, which the API only echoes
 * with EXPOSE_DEV_OTP=on outside a hardened environment (see lib/otp.js). There
 * is no back door here — with the flag off this script cannot log a subject in,
 * which is the correct outcome.
 */
async function subjectSignIn({ fullName, email, group }) {
  const jar = new Jar(email)
  let res = await call(jar, 'POST', '/auth/subject/register', {
    json: { fullName, email, group },
    expect: [200, 201, 409],
  })

  // Already registered from an earlier run — ask for a login code instead.
  if (!res?.devOtp) {
    res = await call(jar, 'POST', '/auth/subject/login', { json: { email } })
  }

  const otp = res?.devOtp ?? res?.otp
  if (!otp) {
    throw new Error(
      `No OTP returned for ${email}. Set EXPOSE_DEV_OTP="on" in backend/.env — ` +
        'this script cannot complete a subject sign-in without it.',
    )
  }

  const verified = await call(jar, 'POST', '/auth/subject/verify', { json: { email, otp } })
  return { jar, masterUserId: verified?.subject?.masterUserId ?? verified?.masterUserId }
}

async function fixture(name) {
  return readFile(path.join(FIXTURES, name))
}

function fileForm(field, filename, buffer, type, extra = {}) {
  const form = new FormData()
  form.append(field, new Blob([buffer], { type }), filename)
  for (const [k, v] of Object.entries(extra)) form.append(k, v)
  return form
}

/** Polls a session until it leaves PROCESSING, so the script reports the real outcome. */
async function waitForSession(jar, sessionId, { timeoutMs = 180_000 } = {}) {
  const deadline = Date.now() + timeoutMs
  let last = null
  while (Date.now() < deadline) {
    const session = await call(jar, 'GET', `/api/v1/sessions/${sessionId}`)
    if (session.status !== last) {
      note(`session status: ${session.status}`)
      last = session.status
    }
    if (!['PROCESSING', 'ACTIVE'].includes(session.status)) return session
    await new Promise((r) => setTimeout(r, 3000))
  }
  note(`still ${last} after ${Math.round(timeoutMs / 1000)}s — leaving it running`)
  return { status: last }
}

/**
 * Waits for the API to answer /health twice in a row, a second apart.
 *
 * Twice, not once: the dev server runs under `node --watch`, so a save bounces
 * it, and a single probe can catch the old process on its way down and then
 * fail the very next call. Two consecutive successes means it is actually up
 * rather than merely still listening.
 */
async function waitForApi({ timeoutMs = 90_000 } = {}) {
  const deadline = Date.now() + timeoutMs
  let consecutive = 0
  let lastError = null

  while (Date.now() < deadline) {
    try {
      const res = await fetch(`${BASE}/health`, { signal: AbortSignal.timeout(3000) })
      consecutive = res.ok ? consecutive + 1 : 0
      if (consecutive >= 2) return
    } catch (err) {
      lastError = err
      consecutive = 0
    }
    await new Promise((r) => setTimeout(r, 1000))
  }

  throw new Error(
    `API at ${BASE} never became ready (${lastError?.message ?? 'no /health'}). ` +
      'Start the stack with `npm run up` from the repository root.',
  )
}

/**
 * Finalises a session: redaction runs, and only then are its frames terminal.
 *
 * This is the step that makes an export possible. Until a session is finalised
 * every photo in it is "unresolved", and projectExport refuses the whole build
 * rather than ship an archive in which the consented subject is the one blurred
 * out. A demo that stops at TAGGING therefore has no exportable data at all,
 * which reads as a broken export rather than an unfinished session.
 */
async function finalize(jar, sessionId, label) {
  try {
    const res = await call(jar, 'POST', `/api/v1/sessions/${sessionId}/finalize`)
    const settled = await waitForSession(jar, sessionId)
    ok(`${label} session finalised — ${settled.status}${res?.written ? `, ${res.written} redacted` : ''}`)
  } catch (err) {
    note(`${label} finalize: ${err.message.slice(0, 240)}`)
  }
}

async function main() {
  console.log(`PRISM demo seed — tag ${TAG}, API ${BASE}`)
  await waitForApi()
  let exportInfo = null

  step(1, 'Signing in as the four admin roles')
  const owner = await adminLogin('dataowner@prism.local')
  const dpo = await adminLogin('dpo@prism.local')
  const agent = await adminLogin('agent@prism.local')
  const dataAdmin = await adminLogin('dataadmin@prism.local')
  ok('dataOwner, dpo, collectionAgent, dataAdmin')

  const agentAdminId = await resolveAgentId(owner)

  step(2, 'DPO authors and publishes the consent notice')
  // A project cannot be submitted without one — assertCollectable refuses, which
  // is the right shape: the notice a principal signs has to exist before anyone
  // is asked to sign it.
  const template = await call(dpo, 'POST', '/api/v1/consent-templates', {
    json: {
      name: `Demo Collection Notice ${TAG}`,
      purpose:
        'Explains what is captured (stills, voice, written notes), why, how long ' +
        'it is kept, and how to withdraw — the notice shown before consent is given.',
      dataTypes: ['FACE', 'VOICE', 'TEXT'],
      retention: '90 days',
      grievanceContact: 'dpo@prism.local',
      bodyByLocale: { en: CONSENT_BODY },
    },
    expect: [200, 201],
  })
  await call(dpo, 'POST', `/api/v1/consent-templates/${template.id}/publish`, { expect: [200, 201] })
  ok(`notice ${template.id} published`)

  step(3, 'dataOwner creates a project and submits it for approval')
  const project = await call(owner, 'POST', '/api/v1/projects', {
    json: {
      consentTemplateId: template.id,
      name: `Demo Collection ${TAG}`,
      purpose:
        'Multimodal capture of consenting volunteers — stills, voice and written ' +
        'notes — for on-device privacy model evaluation. Every participant is ' +
        'enrolled, consented and erasable on request.',
      retention: '90 days',
      dataTypes: ['FACE', 'VOICE', 'TEXT'],
      riskLevel: 'MEDIUM',
    },
  })
  ok(`project ${project.id} "${project.name}"`)
  await call(owner, 'POST', `/api/v1/projects/${project.id}/submit`)
  ok('submitted — now PENDING_APPROVAL')

  step(4, 'DPO approves it')
  await call(dpo, 'POST', `/api/v1/projects/${project.id}/approve`)
  ok('approved — the project is now collectable')

  step(5, 'dataOwner assigns the collection agent')
  await call(owner, 'POST', `/api/v1/projects/${project.id}/assignments`, {
    json: { adminId: agentAdminId },
  })
  ok(`agent ${agentAdminId} assigned`)

  step(6, 'Registering two data principals and capturing their consent')
  const people = [
    { key: 'priya', fullName: `Priya Sharma ${TAG}`, email: `priya.${TAG}@demo.prism.local`, group: 'VOLUNTEER', face: 'solo-a.jpg', voice: 'voice-priya.wav' },
    { key: 'arjun', fullName: `Arjun Mehta ${TAG}`, email: `arjun.${TAG}@demo.prism.local`, group: 'VOLUNTEER', face: 'enroll-b.jpg', voice: 'voice-arjun.wav' },
  ]

  for (const person of people) {
    const { jar, masterUserId } = await subjectSignIn(person)
    person.jar = jar
    person.masterUserId = masterUserId
    await call(jar, 'POST', `/api/v1/consent/projects/${project.id}/grant`)

    // A second, separate act. Project consent says "you may collect me for this
    // purpose"; this says "you may hold a biometric template of my face and
    // voice". enrollment.service refuses every enrolment without it, and only
    // the principal can give it — there is no admin route that sets this flag,
    // which is why the seed signs in as them to do it.
    await call(jar, 'PATCH', '/api/v1/me/biometric-consent', { json: { accepted: true } })
    ok(`${person.fullName} — registered, signed in, project + biometric consent granted`)
  }

  step(7, 'Agent enrols each principal (face, then voice)')
  for (const person of people) {
    const selfie = await fixture(person.face)
    const enrolled = await call(
      agent,
      'POST',
      `/api/v1/subjects/${person.masterUserId}/enrollments`,
      { form: fileForm('selfie', person.face, selfie, 'image/jpeg', { pose: 'FRONT' }), expect: [200, 201] },
    )
    ok(`${person.key}: face enrolled (${enrolled.duplicate ? 'already present' : 'new'})`)

    try {
      const clip = await fixture(person.voice)
      const voice = await call(
        agent,
        'POST',
        `/api/v1/subjects/${person.masterUserId}/voice-enrollments`,
        { form: fileForm('audio', person.voice, clip, 'audio/wav'), expect: [200, 201] },
      )
      ok(`${person.key}: voice enrolled (${voice.duplicate ? 'already present' : 'new'})`)
    } catch (err) {
      // Audio is behind AUDIO_CAPTURE_ENABLED. A stack without it should still
      // produce a usable image demo rather than stopping here.
      note(`${person.key}: voice enrolment skipped — ${err.message.slice(0, 120)}`)
    }
  }

  if (SKIP_MEDIA) {
    summary({ project, people })
    return
  }

  step(8, 'IMAGE session — roster, bulk upload, end')
  const imageSession = await call(agent, 'POST', '/api/v1/sessions', {
    json: { projectId: project.id, location: 'Demo Lab A', type: 'IMAGE' },
  })
  ok(`session ${imageSession.code} (${imageSession.id})`)

  for (const person of people) {
    await call(agent, 'POST', `/api/v1/sessions/${imageSession.id}/participants`, {
      json: { subjectId: person.masterUserId },
      expect: [200, 201, 409],
    })
  }
  ok(`roster: ${people.length} participants`)

  const bulk = new FormData()
  bulk.append('cameraSource', 'IPHONE_UPLOAD')
  let count = 0
  for (let i = 1; i <= 6; i += 1) {
    for (const stem of ['group', 'solo-a']) {
      const name = `${stem}-${String(i).padStart(2, '0')}.jpg`
      bulk.append('photos', new Blob([await fixture(path.join('bulk', name))], { type: 'image/jpeg' }), name)
      count += 1
    }
  }
  const uploaded = await call(agent, 'POST', `/api/v1/sessions/${imageSession.id}/photos`, {
    form: bulk,
    expect: [201, 207],
  })
  ok(`bulk upload: ${uploaded.added} added, ${uploaded.duplicates} duplicate, ${uploaded.failed} failed (of ${count})`)

  await call(agent, 'POST', `/api/v1/sessions/${imageSession.id}/end`)
  ok('session ended — recognition queued')
  const settled = await waitForSession(agent, imageSession.id)
  ok(`image session settled at ${settled.status}`)

  const clusters = await call(agent, 'GET', `/api/v1/sessions/${imageSession.id}/clusters`)
  const rows = clusters.clusters ?? clusters.items ?? []
  ok(
    `clusters: ${rows.length} — ` +
      rows
        .map((c) => `${c.suggestedName ?? 'unmatched'} ${c.faceCount}f ${c.tagStatus}` +
          (c.matchScore ? ` @${c.matchScore.toFixed(2)}` : ''))
        .join(' | '),
  )
  await finalize(agent, imageSession.id, 'image')

  step(9, 'VIDEO — uploaded into its own session')
  let videoSession = null
  try {
    videoSession = await call(agent, 'POST', '/api/v1/sessions', {
      json: { projectId: project.id, location: 'Demo Lab A', type: 'IMAGE' },
    })
    for (const person of people) {
      await call(agent, 'POST', `/api/v1/sessions/${videoSession.id}/participants`, {
        json: { subjectId: person.masterUserId },
        expect: [200, 201, 409],
      })
    }
    const clip = await fixture('clip-group.mp4')
    const video = await call(agent, 'POST', `/api/v1/sessions/${videoSession.id}/videos`, {
      form: fileForm('video', 'clip-group.mp4', clip, 'video/mp4'),
      expect: [200, 201],
    })
    ok(`video ${video.video?.id ?? '(id unknown)'} uploaded`)

    // Nothing analyses a clip on upload. The recognition worker does it when the
    // session ends (recognition.service.js -> analyzeVideo), so a video session
    // left open sits at PENDING_ANALYSIS forever and looks like a broken
    // pipeline rather than an unfinished one.
    await call(agent, 'POST', `/api/v1/sessions/${videoSession.id}/end`)
    const videoSettled = await waitForSession(agent, videoSession.id)
    const videos = await call(agent, 'GET', `/api/v1/sessions/${videoSession.id}/videos`)
    ok(
      `video session settled at ${videoSettled.status} — ` +
        (videos.videos ?? []).map((v) => `${v.id.slice(0, 8)}:${v.status}`).join(', '),
    )
    await finalize(agent, videoSession.id, 'video')
  } catch (err) {
    note(`video step: ${err.message.slice(0, 200)}`)
  }

  step(10, 'AUDIO session — upload, analyse, redact')
  let audioSession = null
  try {
    audioSession = await call(agent, 'POST', '/api/v1/sessions', {
      json: { projectId: project.id, location: 'Studio Booth 1', type: 'AUDIO' },
    })
    for (const person of people) {
      await call(agent, 'POST', `/api/v1/sessions/${audioSession.id}/participants`, {
        json: { subjectId: person.masterUserId },
        expect: [200, 201, 409],
      })
    }
    const wav = await fixture('interview-2speakers.wav')
    const rec = await call(agent, 'POST', `/api/v1/sessions/${audioSession.id}/recordings`, {
      form: fileForm('main_audio', 'interview-2speakers.wav', wav, 'audio/wav'),
      expect: [200, 201],
    })
    const recordingId = rec.recording?.id
    ok(`recording ${recordingId} uploaded (${audioSession.code})`)

    note('analysing — diarisation + transcription + speaker ID + PII (takes ~40s)')
    const analysis = await call(
      agent,
      'POST',
      `/api/v1/sessions/${audioSession.id}/recordings/${recordingId}/analyze`,
    )
    ok(`analysed: ${analysis.segments?.length ?? 0} segments, gallery ${JSON.stringify(analysis.gallery ?? {})}`)

    const redacted = await call(
      agent,
      'POST',
      `/api/v1/sessions/${audioSession.id}/recordings/${recordingId}/redact`,
    )
    ok(`redacted: ${JSON.stringify(redacted).slice(0, 200)}`)
    await finalize(agent, audioSession.id, 'audio')
  } catch (err) {
    note(`audio step: ${err.message.slice(0, 300)}`)
  }

  step(11, 'TEXT session — upload, analyse, redact')
  let textSession = null
  try {
    textSession = await call(agent, 'POST', '/api/v1/sessions', {
      json: { projectId: project.id, location: 'Demo Lab A', type: 'TEXT' },
    })
    for (const person of people) {
      await call(agent, 'POST', `/api/v1/sessions/${textSession.id}/participants`, {
        json: { subjectId: person.masterUserId },
        expect: [200, 201, 409],
      })
    }
    const doc = Buffer.from(DEMO_DOCUMENT, 'utf8')
    // The multer field is `file` — see documents/document.routes.js. The route
    // also accepts a pasted {name, textContent} JSON body; the upload path is
    // used here because that is what the portal's file picker does.
    const created = await call(agent, 'POST', `/api/v1/sessions/${textSession.id}/documents`, {
      form: fileForm('file', 'interview-notes.txt', doc, 'text/plain'),
      expect: [200, 201],
    })
    const documentId = created.document?.id ?? created.id
    ok(`document ${documentId} uploaded (${textSession.code})`)

    const analysed = await call(
      agent,
      'POST',
      `/api/v1/sessions/${textSession.id}/documents/${documentId}/analyze`,
    )
    const entities = analysed.entities ?? []
    ok(
      `analysed: ${entities.length} entities — ` +
        [...new Set(entities.map((e) => e.entity_type))].join(', '),
    )

    // Detection alone redacts nothing: /redact reads SAVED SPANS, and analyze
    // only reports. This is the same step the portal's "Tag all detected"
    // button performs — without it the redacted derivative comes back
    // byte-identical to the original, which reads as a working pipeline right
    // up until someone opens the file.
    await call(agent, 'PUT', `/api/v1/sessions/${textSession.id}/documents/${documentId}/spans`, {
      json: {
        spans: entities.map((e) => ({
          startChar: e.start,
          endChar: e.end,
          action: 'REDACT_PII',
          reason: `PII_${e.entity_type}_DETECTED`,
          piiType: e.entity_type,
          textSnippet: String(e.text ?? '').slice(0, 120),
        })),
      },
    })
    ok(`${entities.length} spans tagged for redaction`)

    await call(agent, 'POST', `/api/v1/sessions/${textSession.id}/documents/${documentId}/redact`)
    ok('redacted')
    await finalize(agent, textSession.id, 'text')
  } catch (err) {
    note(`text step: ${err.message.slice(0, 300)}`)
  }

  step(12, 'dataOwner exports the project')
  try {
    // 202: the build is a queued job, not a synchronous response.
    const requested = await call(owner, 'POST', `/api/v1/projects/${project.id}/exports`, {
      expect: [200, 201, 202, 409],
    })
    if (!requested?.id) {
      note(`export not queued: ${JSON.stringify(requested).slice(0, 300)}`)
    } else {
      ok(`export ${requested.id} queued`)
      const built = await waitForExport(owner, project.id, requested.id)
      if (built.status === 'READY') {
        ok(
          `export READY — ${built.photosWritten}/${built.photosTotal} files, ` +
            `${(built.sizeBytes / 1024).toFixed(0)} KB, sha256 ${String(built.contentHash).slice(0, 16)}…`,
        )
        exportInfo = { id: requested.id, projectId: project.id }
      } else {
        note(`export ${built.status}: ${built.error ?? '(no reason recorded)'}`)
      }
    }
  } catch (err) {
    note(`export step: ${err.message.slice(0, 400)}`)
  }

  summary({ project, people, imageSession, audioSession, textSession, videoSession, exportInfo })
}

/** Polls a queued export until the worker finishes it. */
async function waitForExport(jar, projectId, exportId, { timeoutMs = 240_000 } = {}) {
  const deadline = Date.now() + timeoutMs
  let last = null
  while (Date.now() < deadline) {
    const row = await call(jar, 'GET', `/api/v1/projects/${projectId}/exports/${exportId}`)
    if (row.status !== last) {
      note(`export status: ${row.status}${row.progress ? ` (${row.progress}%)` : ''}`)
      last = row.status
    }
    if (!['QUEUED', 'RUNNING'].includes(row.status)) return row
    await new Promise((r) => setTimeout(r, 3000))
  }
  return { status: last ?? 'UNKNOWN', error: `still ${last} after ${timeoutMs / 1000}s` }
}

/** The same lookup MyProjects.jsx uses to populate its agent picker. */
async function resolveAgentId(jar) {
  const rows = await call(jar, 'GET', '/auth/admin/users?role=collectionAgent')
  const found = (rows?.items ?? []).find((a) => a.email === 'agent@prism.local')
  if (found) return found.id
  throw new Error(
    'No collectionAgent named agent@prism.local. Run scripts/dev-seed-admins.js first.',
  )
}

const CONSENT_BODY = `WHAT WE COLLECT
  Photographs of you, a recording of your voice, and written interview notes,
  captured during a scheduled session with a collection agent.

WHY
  To build an evaluation set for on-device privacy models. Your data is not used
  to train a public model and is not shared outside the project team.

HOW LONG
  90 days from capture, after which it is deleted automatically.

YOUR RIGHTS
  You can see everything held about you, and withdraw at any time, from the
  participant portal. Withdrawal removes your data from this project and
  invalidates any export that contained it.

CONTACT
  dpo@prism.local
`

const DEMO_DOCUMENT = `INTERVIEW NOTES — VOLUNTEER INTAKE

Participant: Priya Sharma
Contact: priya.sharma@example.com / +91 98456 12337
Address: 42 Residency Road, Bangalore 560025
Aadhaar on file: 4321 8765 2109
PAN: ABCDE1234F

Interviewer: Arjun Mehta

Summary
-------
Participant confirmed she is happy for stills and voice to be captured for the
on-device evaluation set. She asked how long the recordings are kept; explained
the 90 day retention on the project and that she can withdraw at any time from
the participant portal.

She mentioned her colleague Rohit Verma may also want to take part. His number
is 90080 44112. No consent captured for him at this stage.

Action: send the participant portal link to priya.sharma@example.com.
`

function summary({ project, people, imageSession, audioSession, textSession, videoSession, exportInfo }) {
  console.log('\n' + '='.repeat(72))
  console.log('DEMO DATA READY')
  console.log('='.repeat(72))
  console.log(`project        ${project.name}`)
  console.log(`               ${project.id}`)
  for (const p of people) console.log(`subject        ${p.fullName}  ${p.masterUserId}`)
  if (imageSession) console.log(`image session  ${imageSession.code}  ${imageSession.id}`)
  if (videoSession) console.log(`video session  ${videoSession.code}  ${videoSession.id}`)
  if (audioSession) console.log(`audio session  ${audioSession.code}  ${audioSession.id}`)
  if (textSession) console.log(`text session   ${textSession.code}  ${textSession.id}`)
  console.log('')
  console.log('Admin portal   http://localhost:5180   (agent@prism.local / dataowner@prism.local)')
  console.log('User portal    http://localhost:5173')
  console.log(`Tagging        http://localhost:5180/sessions/${imageSession?.id ?? ':id'}/tagging`)
  console.log(`Processed data http://localhost:5180/processed-data`)
  console.log('')
}

main().catch((err) => {
  console.error(`\nFAILED: ${err.message}`)
  process.exit(1)
})
